UI cleanup in the auth screen
kodecocodes/aat-materials pull request #5
Opened 2021-07-09 08:49 UTC by hackertronix

@alexsullivan114, I fixed some styling related things in this PR alongside the tweaks to the movie item

2021-07-12 06:44 UTC, filbabic requested changes
Hey!

Can you make sure to use the same formatting as in the project (XML also uses 2 spaces for its ind. so it's more visible if we have to show it in the book).

I think you've formatted to four here. We can all just use the project style and it should be fine!

2021-07-14 15:48 UTC, hackertronix commented
@filbabic fixed! 🙌

2021-07-14 16:06 UTC, filbabic approved these changes, later dismissed

2021-07-14 18:23 UTC, alexsullivan114 approved these changes

2021-07-14 18:24 UTC, merged